### PR TITLE
feat: add get_timezone_by_ip()

### PR DESCRIPTION
**Pull request by uniartisan**
This function adds a request network interface, and tries to get the current time zone through the network interface. This requires the installer to have a network, and when there is no network, the original solution will be tried.

This may cause, in the worst case, the UI display is blocked for 3s

### CODE REVIEW

**Comment by mirkobrombin** [comment]
Hi, thanks for the contribution but we do not use custom css, it's rememant from the first setup, we used it as a base. We can remove the css part entirely now.

**Comment by uniartisan** [comment]
> Hi, thanks for the contribution but we do not use custom css, it's rememant from the first setup, we used it as a base. We can remove the css part entirely now. 

thanks for your reply, it seems like you have comment in the wrong topic.(maybe another pull request is the proper one.

This pull requestaims to enhance user experience, but i don't know how to solve    http request in async way. i have tried, but not works, so i list the worst impact there.

**Comment by mirkobrombin** [comment]
I was sure I had answered the right one, but I was reading another one before. I noticed that Github has some browsing problems lately when browsing the browser history. I move the comment of there.

**Comment by mirkobrombin** [comment]
I made the RunAsync class to achieve async in the application, it’s just using threading. 

However, I can see a problem in your integration, for example if the user's connection is under a proxy, it could still result in the wrong time zone. I think it's a good improvement anyway and I'll test it soon, I also ping @matbme and @Muqtxdir

**Comment by matbme** [comment]
>  if the user's connection is under a proxy, it could still result in the wrong time zone

I think this is rare enough that it's fine to ignore. Besides, a proxy user will probably have issues with geolocation in many other applications as well.

**Comment by uniartisan** [comment]
Yes, this may be affected by the proxy, considering this is the first installation, maybe this does not affect?

Or check the http_proxy environment variable, if there is one, don't use this function or issue a prompt, I think even this will help when installing for the first time.

**Comment by uniartisan** [comment]
Let's look at the current implementation, now use asynchronous completion of related operations, and change the UI selection through signals after the operation is completed

**Comment by Muqtxdir** [comment]
I agree with @matbme and @uniartisan that proxy connection during install is very unlikely and rare.so this works out

**Review by mirkobrombin — APPROVED** [review]

**Comment by mirkobrombin** [comment]
code looks good, I'll test it later in a vm

**Pull request merged**
