### PR TITLE
fix: fix a bug in provider.load_from_data

### PR DESCRIPTION
**Pull request by uniartisan**
Fix css-provider getting too many arguments

http://lazka.github.io/pgi-docs/#Gtk-3.0/classes/CssProvider.html#Gtk.CssProvider.load_from_data

### CODE REVIEW

**Comment by mirkobrombin** [comment]
Hi, thanks for the contribution but we do not use custom css, it's rememant from the first setup, we used it as a base. We can remove the css part entirely now.

**Comment by uniartisan** [comment]
Thanks a lot for getting the specifics, the fix is because on my platform it doesn't work correctly due to this bug.
When upstream changes are relevant, I will follow up upstream and close this pull request.
thank you very much for replying me :)

**Comment by Muqtxdir** [comment]
Hi @uniartisan 

Could you look into removing the CSS provider part in this PR as already pointed above that it's not at all used in the installer

**Comment by uniartisan** [comment]
https://github.com/Vanilla-OS/vanilla-installer/pull/163/commits/aec3b9509bd0a87a2050bbb75bf3f229e8d78f6a

I don't know if this meets your wishes, I have tested related changes.


> Hi @uniartisan
> 
> Could you look into removing the CSS provider part in this PR as already pointed above that it's not at all used in the installer

**Review by Muqtxdir — APPROVED** [review]
thanks!

**Review by kbdharun — APPROVED** [review]

**Pull request merged**
