### PR TITLE
feat:[close #349] Feature Request: Let choose multiple keyboard layouts

### LINKED ISSUE #349: Feature Request: Let choose multiple keyboard layouts
In countries with non-Latin alphabet it is very common to have both English and native keyboard layouts. But the installer only allows to choose one.

### PR DESCRIPTION
**Pull request by muhdsalm**
closes #349

### CODE REVIEW

**Comment by muhdsalm** [comment]
The title's been changed to closed but the PRs not been merged.

**Comment by taukakao** [comment]
> The title's been changed to closed but the PRs not been merged.

"close" here just means that merging this will close #349 
Usually, we would use "fix" here but it's not a bug so "close" is more appropriate

**Review by mirkobrombin — APPROVED** [review]
Looks good to me. I'll wait for a second opinion from Mat who recently changed those files.

**Comment by matbme** [comment]
Something's weird with the checkboxes. Apparently it only updates the selected layouts if I press the row itself.

[Screencast from 2024-06-17 14-43-10.webm](https://github.com/Vanilla-OS/vanilla-installer/assets/48367298/4e5e7a48-d9ad-4230-9482-f3dc93f89e03)

**Comment by mirkobrombin** [comment]
The proper signal should be `toggled` https://docs.gtk.org/gtk3/class.CheckButton.html

**Comment by muhdsalm** [comment]
Selecting the already existing layout would be confusing since you can select multiple keyboard layouts so you wouldn't know English US is already selected. So should we stop automatically selecting the existing layout?

**Comment by mirkobrombin** [comment]
I would remove the default. Ofc, the "next" button should be disabled if nothing is selected

**Comment by muhdsalm** [comment]
It's weird no one pointed out it failed in the finals, but it's fixed now.

**Comment by mirkobrombin** [comment]
image

I was testing and my eyes fell on the test field below. It is not clear to me what I am testing, which of the 2 layouts I have chosen (en/it)

**Comment by muhdsalm** [comment]
The one you choose first becomes your default keyboard, and in Gnome you can choose between them with a dialog in the top right. Does the reduced session have the choosing dialog?

**Comment by mirkobrombin** [comment]
Ah you are right, yeah probably not so easy to understand but I think it is fine for now. Anyway can you squash into a single commit?

**Comment by muhdsalm** [comment]
Roger that, sir!

**Pull request merged**
