### PR TITLE
feat [close #283]: add link to documentation; fu: update handbook button in recovery panel

### LINKED ISSUE #283: Feature request: add link to Documentation website

### PR DESCRIPTION
**Pull request by kbdharun**

### CODE REVIEW

**Comment by Muqtxdir** [comment]
hello @kbdharun 

id be nicer if you could attach a screenshot of your introduced change in this pr

**Comment by kbdharun** [comment]
> hello @kbdharun
> 
> id be nicer if you could attach a screenshot of your introduced change in this pr

Sure, I will add a screenshot of the addition.

**Comment by kbdharun** [comment]
Here you go (took this from Workbench; IG we can change the icon to differentiate from the handbook one)

image

**Comment by kbdharun** [comment]
For Handbook, I think we can go with the `accessories-dictionary-symbolic` platform icon.

It would look like this

image

**Review by Muqtxdir — APPROVED** [review]

**Pull request merged**
