### PR TITLE
feat: [close #212] Improve timezone names

### LINKED ISSUE #212: Use localized timezone name
Use `gweather_location_get_name` to get the timezone name localized into its native language e.g. "Sao Paulo" becomes "São Paulo".

### PR DESCRIPTION
**Pull request by matbme**
This PR reworks the timezone UI to better display city names, separated by country.

Closes #212

### CODE REVIEW

**Comment by Muqtxdir** [comment]
hi @matbme 

the page automatically found that my timezone is `Asia/Kolkata` but the `TimezoneRow` doesn't seem to be pre-selected  (_checkbutton toggled state_) like before :thinking: 

image

**Comment by matbme** [comment]
Did it select a different city closer to you by any chance? The new logic lists all cities from GWeather and tries to find the nearest one based on the latitude and longitude returned by 'ip-api'.

**Comment by Muqtxdir** [comment]
its selecting `Asia/Kolkata`  properly not any other city and set `btn_next` to active but it aint setting that checkbutton toggle to active

**Review by Muqtxdir — APPROVED** [review]
nice new look for the page along with new changes!

**Pull request merged**
